apiVersion: apps/v1
kind: Deployment

metadata:
  name: mern-devops-app

spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  selector:
    matchLabels:
      app: mern-devops-app

  template:
    metadata:
      labels:
        app: mern-devops-app

    spec:
      automountServiceAccountToken: false
      containers:
      - name: mern-devops-container

        image: ECR_REPO

        ports:
        - containerPort: 3000

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            ephemeral-storage: 1Gi
          limits:
            memory: 256Mi

        readinessProbe:
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /status
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10